services:
  mysql-db:
    image: mysql:8.0
    container_name: db_hitech
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_AUTHENTICATION_PLUGIN: 'sha256_password'
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: --innodb-use-native-aio=0 --pid-file=/var/run/mysqld/mysqld.pid

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: mysql-db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    container_name: backend_hitech
    ports:
      - '3001:3001'
    depends_on:
      - mysql-db

volumes:
  mysql-data:
