name: HiTech-Solutions CI/CD Pipeline Backend and Frontend

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    backend-test-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  cache: "npm"
                  cache-dependency-path: "HiTech-Solutions/Backend/package-lock.json"

            - name: Execute Backend Unit tests
              run: |
                  npm ci
                  npm run test
                  npm run build
              working-directory: ./HiTech-Solutions/Backend

    frontend-test-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  cache: "npm"
                  cache-dependency-path: "HiTech-Solutions/Frontend/package-lock.json"

            - name: Install dependencies
              run: npm ci
              working-directory: ./HiTech-Solutions/Frontend

            - name: Execute Frontend Unit tests
              run: npm run test:unit
              working-directory: ./HiTech-Solutions/Frontend

            - name: Build the project
              run: npm run build
              working-directory: ./HiTech-Solutions/Frontend
