name: Build and Deploy App to Azure - HiTech-Solutions

on:
    push:
        branches:
            - deployAutomation
    workflow_dispatch:

jobs:
    frontend-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"
                  cache-dependency-path: "HiTech-Solutions/Frontend/package-lock.json"
            - name: Install dependencies
              run: npm ci
              working-directory: ./HiTech-Solutions/Frontend
            - name: Execute Frontend Unit tests
              run: npm run test:unit
              working-directory: ./HiTech-Solutions/Frontend

    build-frontend:
        runs-on: ubuntu-latest
        needs: frontend-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"
                  cache-dependency-path: "HiTech-Solutions/Frontend/package-lock.json"
            - name: Install dependencies
              run: npm ci
              working-directory: ./HiTech-Solutions/Frontend
            - name: Build the project
              run: npm run build
              working-directory: ./HiTech-Solutions/Frontend
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: ./HiTech-Solutions/Frontend/build

    build-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Log in to registry
              uses: docker/login-action@v2
              with:
                  registry: https://index.docker.io/v1/
                  username: ${{ secrets.AzureAppService_ContainerUsername }}
                  password: ${{ secrets.AzureAppService_ContainerPassword }}
            - name: Build and push container image to registry
              uses: docker/build-push-action@v3
              with:
                  context: ./HiTech-Solutions/Backend
                  file: ./HiTech-Solutions/Backend/Dockerfile
                  push: true
                  tags:
                      "index.docker.io/${{
                      secrets.AzureAppService_ContainerUsername }}/app:${{
                      github.sha }}"

    deployment:
        runs-on: ubuntu-latest
        needs: [build-frontend, build-backend]
        environment:
            name: "production"
        steps:
            - name: Download frontend artifact
              uses: actions/download-artifact@v3
              with:
                  name: node-app
            - name: Deploy Frontend to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-solutions"
                  slot-name: "Production"
                  package: .
            - name: Deploy Backend to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-backend"
                  slot-name: "production"
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
                  images:
                      "index.docker.io/${{
                      secrets.AzureAppService_ContainerUsername }}/app:${{
                      github.sha }}"
