name: Build and deploy Node.js app to Azure Web App - hitech-backend

on:
    push:
        branches:
            - deployAutomation
    workflow_dispatch:

jobs:
    backend-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Install dependencies and run tests
              run: |
                  npm install
                  npm run test --if-present
              working-directory: ./HiTech-Solutions/Backend

    build-backend:
        runs-on: ubuntu-latest
        needs: backend-test
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Build the project
              run: |
                  npm install
                  npm run build --if-present
              working-directory: ./HiTech-Solutions/Backend
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: ./HiTech-Solutions/Backend/dist

    deploy-backend:
        runs-on: ubuntu-latest
        needs: build-backend
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: node-app
            - name: Unpack and prepare for deployment
              run: |
                  mkdir -p deployment
                  tar -xvf node-app -C deployment
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-backend"
                  slot-name: "Production"
                  package: .
