name: Build and deploy Node.js app to Azure Web App - hitech-backend

on:
    push:
        branches:
            - deployAutomation
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm run test --if-present
              working-directory: ./HiTech-Solutions/Backend # Ensure this is the correct path

            - name: Zip artifact for deployment
              run: zip -r release.zip ./*
              working-directory: ./HiTech-Solutions/Backend # Ensure zipping the correct directory

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: node-app
                  path: ./HiTech-Solutions/Backend/release.zip # Ensure correct path for the zipped file

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip
              working-directory: .

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id:
                      ${{
                      secrets.AZUREAPPSERVICE_CLIENTID_F925AC26776146B6AD2734F821F5FD0F
                      }}
                  tenant-id:
                      ${{
                      secrets.AZUREAPPSERVICE_TENANTID_7B2E94FDBE4544589BFC5602B667A3E0
                      }}
                  subscription-id:
                      ${{
                      secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6168A2995F146C58F691025BE875F26
                      }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-backend"
                  slot-name: "Production"
                  package: .
