name: Deploy NestJS Backend to Azure Web App

on:
    push:
        branches:
            - deployAutomation # Mettez à jour selon la branche qui doit déclencher le déploiement
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm install
              working-directory: ./HiTech-Solutions/Backend # Mettez à jour selon le chemin relatif de votre backend dans le dépôt

            - name: Build application
              run: npm run build
              working-directory: ./HiTech-Solutions/Backend # Assurez-vous que ce chemin est correct

            - name: Run tests
              run: npm run test
              working-directory: ./HiTech-Solutions/Backend # Optionnel, supprimez cette étape si vous n'avez pas de tests

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: hitech-backend # Remplacez par le nom de votre Azure Web App
                  slot-name: Production # Optionnel, supprimez si vous ne déployez pas sur un slot spécifique
                  package: .
                  publish-profile:
                      ${{
                      secrets.AZUREAPPSERVICE_PUBLISHPROFILE_112CE37252BA4624A16A2CF55653B573
                      }}
