name: Build and deploy Node.js app to Azure Web App - hitech-backend

on:
    push:
        branches:
            - deployAutomation
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build  
                  npm run test 
              working-directory: ./HiTech-Solutions/Backend

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-backend"
                  slot-name: "Production"
                  package: ./HiTech-Solutions/Backend
                  publish-profile:
                      ${{
                      secrets.AZUREAPPSERVICE_PUBLISHPROFILE_112CE37252BA4624A16A2CF55653B573
                      }}
