name: Build and deploy Node.js app to Azure Web App - hitech-backend

on:
    push:
        branches:
            - deployAutomation
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    backend-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Install dependencies and run tests
              run: |
                  npm install
                  npm run test
              working-directory: ./HiTech-Solutions/Backend

    build-backend:
        runs-on: ubuntu-latest
        needs: backend-test
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Build the project
              run: |
                  npm install
                  npm run build --if-present
              working-directory: ./HiTech-Solutions/Backend

    deploy-backend:
        runs-on: ubuntu-latest
        needs: build-backend
        steps:
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F925AC26776146B6AD2734F821F5FD0F }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B2E94FDBE4544589BFC5602B667A3E0 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6168A2995F146C58F691025BE875F26 }}
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "hitech-backend"
                  slot-name: "Production"
                  package: ."
