name: Build and deploy Node.js app to Azure Web App - hitech-backend

on:
  push:
    branches:
      - deployAutomation
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./HiTech-Solutions/Backend

      - name: Build
        run: npm run build --if-present
        working-directory: ./HiTech-Solutions/Backend

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF49DCDAD604472A996E4D04A019CACB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_92EF8484E6054718A2D5E3462A29AF6A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B42A81D5A9334C2FBD51DCF3C6B7B2D9 }}
          auth-type: oidc

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hitech-backend'
          slot-name: 'Production'
          package: ./HiTech-Solutions/Backend/dist
