# Documentation pour l'action Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# Plus d'actions GitHub pour Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hitech-solutions

on:
  push:
    branches:
      - deployAutomation
  workflow_dispatch:

jobs:
  build-backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: "npm"
          cache-dependency-path: "HiTech-Solutions/Backend/package-lock.json"
          
      - name: Execute Backend Unit tests
        run: |
            npm ci
            npm run test
            npm run build
        working-directory: ./HiTech-Solutions/Backend

  build-frontend-test:
    runs-on: ubuntu-latest
    needs: build-backend-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: "npm"
          cache-dependency-path: "HiTech-Solutions/Frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./HiTech-Solutions/Frontend

      - name: Execute Frontend Unit tests
        run: npm run test:unit
        working-directory: ./HiTech-Solutions/Frontend

      - name: Build the project
        run: npm run build
        working-directory: ./HiTech-Solutions/Frontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./HiTech-Solutions/Frontend/build

  deployment:
    runs-on: ubuntu-latest
    needs: build-frontend-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66887E203DBB4DD49F6052FA2478675A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C92C8C9EBF5346D5A82E4C86A72DFE39 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17BA94BAEA184088A15DFDA42CBD1720 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'hitech-solutions'
          slot-name: 'Production'
          package: .
