# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: HiTech-Solutions CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 frontend-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: 'HiTech-Solutions/Frontend/package-lock.json'

      - name: Execute Cypress E2E tests
        uses: cypress-io/github-action@v5
        timeout-minutes: 5
        with:
          working-directory: ./HiTech-Solutions/Frontend
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          browser: chrome
          spec: 'cypress/**/*.cy.js'

      - name: Execute Frontend Unit tests
        run: |
          npm ci
          npm run test:unit
          npm run build
        working-directory: ./HiTech-Solutions/Frontend
